
// @/lib/food-data.ts

export interface FoodItem {
  id: string;
  name: string;
  ig: string; // Indice Glycémique
  isFavorite: boolean;
  isDisliked: boolean;
  isAllergenic: boolean;
}

export interface FoodCategory {
  categoryName: string;
  items: FoodItem[];
}

export const initialFoodCategories: FoodCategory[] = [
  {
    categoryName: "Fruits",
    items: [
      { id: "fruit1", name: "Abricot", ig: "(IG: ~34)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit2", name: "Avocat", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit3", name: "Baies (Myrtilles, Framboises, Mûres, Groseilles)", ig: "(IG: ~25-40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit4", name: "Cerises", ig: "(IG: ~22)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit5", name: "Clémentine/Mandarine", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit6", name: "Coing", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit7", name: "Figue fraîche", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit8", name: "Fraises", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit9", name: "Grenade", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit10", name: "Kiwi", ig: "(IG: ~50)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit11", name: "Nectarine", ig: "(IG: ~43)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit12", name: "Orange", ig: "(IG: ~43)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit13", name: "Pamplemousse", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit14", name: "Papaye", ig: "(IG: ~56)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit15", name: "Pêche", ig: "(IG: ~42)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit16", name: "Poire", ig: "(IG: ~38)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit17", name: "Pomme", ig: "(IG: ~38)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit18", name: "Prune", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fruit19", name: "Raisin", ig: "(IG: ~46-59)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Légumes",
    items: [
      { id: "veg1", name: "Ail", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg2", name: "Artichaut", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg3", name: "Asperge", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg4", name: "Aubergine", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg5", name: "Betterave (crue)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg6", name: "Betterave (cuite)", ig: "(IG: ~64)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg7", name: "Blette", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg8", name: "Brocoli", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg9", name: "Carotte (crue)", ig: "(IG: ~16)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg10", name: "Carotte (cuite)", ig: "(IG: ~39)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg11", name: "Céleri branche", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg12", name: "Céleri rave (cuit)", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg13", name: "Champignons (tous types)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg14", name: "Chou (tous types: blanc, rouge, frisé, kale, romanesco, de Bruxelles)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg15", name: "Chou-fleur", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg16", name: "Concombre", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg17", name: "Courge (Butternut, Spaghetti, Potimarron)", ig: "(IG: ~51-75)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg18", name: "Courgette", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg19", name: "Cresson", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg20", name: "Endive", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg21", name: "Épinards", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg22", name: "Fenouil", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg23", name: "Haricots verts", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg24", name: "Laitue/Salades vertes (tous types: romaine, batavia, feuille de chêne)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg25", name: "Mâche", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg26", name: "Navet (cuit)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg27", name: "Oignon", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg28", name: "Panais (cuit)", ig: "(IG: ~52)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg29", name: "Patates douces (cuites)", ig: "(IG: ~50)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg30", name: "Petit pois (frais)", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg31", name: "Poireau", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg32", name: "Poivron (tous types)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg33", name: "Radis", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg34", name: "Roquette", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg35", name: "Salsifis (cuit)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg36", name: "Tomate", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "veg37", name: "Topinambour (cuit)", ig: "(IG: ~50)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Fruits à coque et Graines",
    items: [
      { id: "nut1", name: "Amandes", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut2", name: "Graines de chia", ig: "(IG: ~1)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut3", name: "Graines de courge", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut4", name: "Graines de lin", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut5", name: "Graines de pavot", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut6", name: "Graines de sésame", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut7", name: "Graines de tournesol", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut8", name: "Noisettes", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut9", name: "Noix", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut10", name: "Noix de cajou", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut11", name: "Noix de macadamia", ig: "(IG: ~10)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut12", name: "Noix de pécan", ig: "(IG: ~10)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut13", name: "Noix du Brésil", ig: "(IG: ~1)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut14", name: "Pignons de pin", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "nut15", name: "Pistaches", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Céréales, Grains et Féculents",
    items: [
      { id: "grain1", name: "Avoine (flocons)", ig: "(IG: ~55)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain2", name: "Blé (Ebly, grains entiers)", ig: "(IG: ~45)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain3", name: "Boulgour", ig: "(IG: ~48)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain4", name: "Crêpe de sarrasin", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain5", name: "Fonio", ig: "(IG: ~55)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain6", name: "Millet", ig: "(IG: ~55)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain7", name: "Orge perlé", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain8", name: "Pain de blé entier (100%)", ig: "(IG: ~51)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain9", name: "Pain de seigle complet", ig: "(IG: ~45)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain10", name: "Pain au levain (complet)", ig: "(IG: ~53)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain11", name: "Pâtes complètes (al dente)", ig: "(IG: ~40-50)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain12", name: "Pâtes de lentilles corail", ig: "(IG: ~22)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain13", name: "Petit épeautre", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain14", name: "Quinoa (cuit)", ig: "(IG: ~53)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain15", name: "Riz basmati complet", ig: "(IG: ~45)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain16", name: "Riz rouge", ig: "(IG: ~55)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain17", name: "Riz sauvage", ig: "(IG: ~45)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain18", name: "Sarrasin (Kasha)", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain19", name: "Semoule de blé dur complète (couscous complet)", ig: "(IG: ~45)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain20", name: "Son d'avoine", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "grain21", name: "Teff", ig: "(IG: ~57)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Légumineuses",
    items: [
      { id: "legume1", name: "Fèves (cuites)", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume2", name: "Flageolets (cuits)", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume3", name: "Haricots (blancs, rouges, noirs, pinto, azuki - cuits)", ig: "(IG: ~30-40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume4", name: "Lentilles (vertes, brunes, corail - cuites)", ig: "(IG: ~25-30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume5", name: "Lupin", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume6", name: "Pois cassés (cuits)", ig: "(IG: ~22)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume7", name: "Pois chiches (cuits)", ig: "(IG: ~28)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "legume8", name: "Soja (edamame, fèves)", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Viandes, Volailles, Poissons et Œufs",
    items: [
      { id: "meat1", name: "Agneau (maigre)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat2", name: "Bœuf (maigre: steak haché 5%, rumsteck, filet)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat3", name: "Cabillaud", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat4", name: "Colin/Lieu", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat5", name: "Crevettes/Gambas", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat6", name: "Dinde (escalope, filet)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat7", name: "Dorade", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat8", name: "Faisan", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat9", name: "Hareng", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat10", name: "Lapin", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat11", name: "Lotte", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat12", name: "Maquereau", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat13", name: "Merlan", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat14", name: "Moules", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat15", name: "Œufs", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat16", name: "Pintade", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat17", name: "Poitrine de poulet (sans peau)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat18", name: "Porc (filet mignon)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat19", name: "Sardines (fraîches ou en conserve au naturel)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat20", name: "Saumon", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat21", name: "Sole", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat22", name: "Thon (au naturel)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat23", name: "Truite", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "meat24", name: "Veau (escalope, noix)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Produits Laitiers et Alternatives Végétales",
    items: [
      { id: "dairy1", name: "Fromage blanc (nature, 0-3% MG)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy2", name: "Fromage frais (type St Moret, Carré Frais, nature)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy3", name: "Fromages affinés (chèvre frais, comté, emmental, etc. - avec modération)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy4", name: "Kéfir de lait (nature)", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy5", name: "Lait d'amande (non sucré)", ig: "(IG: ~25)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy6", name: "Lait de coco (non sucré, avec modération)", ig: "(IG: ~40)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy7", name: "Lait de noisette (non sucré)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy8", name: "Lait de soja (non sucré)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy9", name: "Lait écrémé ou demi-écrémé", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy10", name: "Petits suisses (nature, 0-3% MG)", ig: "(IG: ~30)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy11", name: "Skyr (nature)", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy12", name: "Tofu (nature, fumé)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy13", name: "Yaourt de brebis (nature)", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy14", name: "Yaourt de chèvre (nature)", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy15", name: "Yaourt grec (nature, sans sucre)", ig: "(IG: ~15)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy16", name: "Yaourt nature (lait de vache)", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "dairy17", name: "Yaourt végétal (soja, amande, coco - nature, non sucré)", ig: "(IG: ~20-35)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Matières Grasses (avec modération)",
    items: [
      { id: "fat1", name: "Beurre de cacahuète (nature, sans sucre ajouté)", ig: "(IG: ~14)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat2", name: "Beurre d'amande/noisette (nature, sans sucre ajouté)", ig: "(IG: <10)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat3", name: "Ghee (beurre clarifié)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat4", name: "Huile de colza", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat5", name: "Huile de lin", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat6", name: "Huile de noix", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat7", name: "Huile d'olive (vierge extra)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat8", name: "Margarine végétale (non hydrogénée, riche en oméga-3)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
      { id: "fat9", name: "Olives", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  },
  {
    categoryName: "Assaisonnements et Autres",
    items: [
        { id: "other1", name: "Bouillon de légumes/volaille (dégraissé, pauvre en sel)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other2", name: "Cacao en poudre (non sucré)", ig: "(IG: ~20)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other3", name: "Cannelle", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other4", name: "Citronnelle", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other5", name: "Clou de girofle", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other6", name: "Concentré de tomate (sans sucre ajouté)", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other7", name: "Coriandre (graines ou fraîche)", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other8", name: "Cumin", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other9", name: "Curcuma", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other10", name: "Curry en poudre", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other11", name: "Échalote", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other12", name: "Gingembre (frais ou en poudre)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other13", name: "Gomasio (sésame grillé et sel)", ig: "(IG: ~35)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other14", name: "Herbes fraîches/sèches (persil, basilic, thym, romarin, aneth, ciboulette, menthe, origan)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other15", name: "Jus de citron/lime", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other16", name: "Levure maltée/nutritionnelle", ig: "(IG: <10)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other17", name: "Moutarde (sans sucre ajouté)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other18", name: "Muscade", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other19", name: "Paprika", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other20", name: "Piment (doux, fort)", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other21", name: "Poivre (noir, blanc, rose)", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other22", name: "Raifort", ig: "(IG: <15)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other23", name: "Sauce soja/tamari (pauvre en sel)", ig: "(IG: <20)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other24", name: "Sel (avec modération, iodé de préférence)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other25", name: "Stevia ou autres édulcorants non caloriques (avec modération)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other26", name: "Vanille (extrait ou gousse, non sucrée)", ig: "(IG: 0)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other27", name: "Vinaigre (de cidre, balsamique, de vin - sans sucre ajouté)", ig: "(IG: <5)", isFavorite: false, isDisliked: false, isAllergenic: false },
        { id: "other28", name: "Wasabi", ig: "(IG: ~10)", isFavorite: false, isDisliked: false, isAllergenic: false },
    ],
  }
].map(category => ({
  ...category,
  items: category.items.sort((a, b) => a.name.localeCompare(b.name))
}));
